"""blog_publications table

Static HTML blogs generated by the LLM and deployed to Vercel.
Each row points to a company and (optionally) the PurchasedDomain whose
subdomain (`blog.<email_domain>`) is used as the public URL.

Revision ID: 0006
Revises: 0005
Create Date: 2026-05-09 20:00:00
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0006"
down_revision: str | None = "0005"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "blog_publications",
        sa.Column("id", sa.String(length=36), primary_key=True),
        sa.Column(
            "company_id",
            sa.String(length=36),
            sa.ForeignKey("companies.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "purchased_domain_id",
            sa.String(length=36),
            sa.ForeignKey("purchased_domains.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column("subdomain_host", sa.String(length=255), nullable=True),
        sa.Column("custom_url", sa.String(length=512), nullable=True),
        sa.Column("vercel_project_name", sa.String(length=255), nullable=True),
        sa.Column("vercel_deployment_id", sa.String(length=128), nullable=True),
        sa.Column("vercel_deployment_url", sa.String(length=512), nullable=True),
        sa.Column("html_content", sa.Text(), nullable=True),
        sa.Column("title", sa.String(length=512), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False, server_default="draft"),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("raw_response", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.create_index(
        "ix_blog_publications_company_id",
        "blog_publications",
        ["company_id"],
    )


def downgrade() -> None:
    op.drop_index("ix_blog_publications_company_id", table_name="blog_publications")
    op.drop_table("blog_publications")
